//images
export default IMAGES = {
  avatar: require('../../assets/images/avatar.png'),
  card: require('../../assets/images/card.jpg'),
  logo: require('../../assets/images/diu-logo.png'),
  hero: require('../../assets/images/hero-logo.png'),
  lecture: require('../../assets/images/lecture.png'),
  mortarboard: require('../../assets/images/mortarboard.png'),
  onlineCourse: require('../../assets/images/online-course.png'),
  pathway: require('../../assets/images/pathway.jpg'),
  promotion: require('../../assets/images/promotion.png'),
  success: require('../../assets/images/success.jpg'),
  teaching: require('../../assets/images/teaching.png'),
  wishlist: require('../../assets/images/wishlist.png'),
  courses: require('../../assets/images/courses.png'),
  slider01: require('../../assets/images/slider01.jpg'),
  slider02: require('../../assets/images/slider02.jpg'),
  slider03: require('../../assets/images/slider03.png'),
  slider04: require('../../assets/images/slider04.jpg'),
  slider05: require('../../assets/images/slider05.jpg'),
  slider06: require('../../assets/images/slider06.jpg'),
};
